// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpxURvVDQhMf3Jkx3ix3mRPAxguxQWTI',
    appId: '1:311910419748:web:441b465a773374d142f7b1',
    messagingSenderId: '311910419748',
    projectId: 'swaply-cc9a7',
    authDomain: 'swaply-cc9a7.firebaseapp.com',
    storageBucket: 'swaply-cc9a7.firebasestorage.app',
    measurementId: 'G-G9QVC6Z6XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEb8hDFwnSCd-YdnwerYI4arkhHCQ47s',
    appId: '1:311910419748:android:270cf4bafad7b64442f7b1',
    messagingSenderId: '311910419748',
    projectId: 'swaply-cc9a7',
    storageBucket: 'swaply-cc9a7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJ81tAoGH1T5k7qfqNnZo7Q9XeiVwWFE',
    appId: '1:311910419748:ios:6405e6b9e27e045f42f7b1',
    messagingSenderId: '311910419748',
    projectId: 'swaply-cc9a7',
    storageBucket: 'swaply-cc9a7.firebasestorage.app',
    iosBundleId: 'com.example.swaply',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzJ81tAoGH1T5k7qfqNnZo7Q9XeiVwWFE',
    appId: '1:311910419748:ios:6405e6b9e27e045f42f7b1',
    messagingSenderId: '311910419748',
    projectId: 'swaply-cc9a7',
    storageBucket: 'swaply-cc9a7.firebasestorage.app',
    iosBundleId: 'com.example.swaply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpxURvVDQhMf3Jkx3ix3mRPAxguxQWTI',
    appId: '1:311910419748:web:2cbaf9d2f86cf9e342f7b1',
    messagingSenderId: '311910419748',
    projectId: 'swaply-cc9a7',
    authDomain: 'swaply-cc9a7.firebaseapp.com',
    storageBucket: 'swaply-cc9a7.firebasestorage.app',
    measurementId: 'G-4N1Q2T84GL',
  );
}
